# This is a simple wrapper for eng/pipeline.yml to get around the limitation of
# user-defined variables not being available in yaml template expressions.

# Parameters ARE available in template expressions, and parameters can have default values,
# so they can be used to control yaml flow.
#

variables:

  # clean the local repo on the build agents
  Build.Repository.Clean: true


  _PublishUsingPipelines: true
  _DotNetArtifactsCategory: WINDOWSDESKTOP

# This is set in the pipeline directly 
# When set to false, CI tests will not be enabled in builds. 
#
# _ContinuousIntegrationTestsEnabled: false

# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
#
# only trigger ci builds for the master and release branches
trigger:
  batch: true 
  branches:
    include: 
    - master
    - release/3.0
    # - arcade
  paths:
    exclude:
    - Documentation/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/3.0
  paths:
    exclude:
    - Documentation/*

# Call the pipeline.yml template, which does the real work
jobs:
- template: /eng/pipeline.yml
  parameters:
    ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      # agent pool can't be read from a user-defined variable (Azure DevOps limitation)
      pool:
        name: NetCoreInternal-Pool
        queue: buildpool.windows.10.amd64.vs2019.pre
      # runAsPublic is used in expressions, which can't read from user-defined variables
      runAsPublic: false

